name: Run Multiple Containers

on: [push]

jobs:
  run-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Network
        run: |
          docker network create my-network

      - name: Run Apache Server Container
        run: |
          docker run -d --name apache-server --network my-network httpd:latest

      - name: Run Curl Container
        run: |
          docker run --rm --network my-network curlimages/curl:latest curl -I http://apache-server
