name: Example Workflow

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run Docker container
        id: run-container
        run: |
          docker network create my_network
          docker run -d --network my_network --name apache-container httpd:latest
          echo "Apache container is running on network my_network"

      - name: Get container URL
        id: container-info
        run: echo "::set-output name=container-url::http://apache-container:80"

  curl-command:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Install curl
        run: sudo apt-get install -y curl

      - name: Run curl command
        run: |
          container_url=${{ needs.setup.outputs.container-url }}
          echo "Sending curl request to $container_url"
          curl -X GET $container_url

  stop-container:
    runs-on: ubuntu-latest
    needs: curl-command
    steps:
      - name: Stop and remove Docker container
        run: |
          docker stop apache-container
          docker rm apache-container
          docker network rm my_network
