name: Example Workflow

on: [push]

jobs:
  start-container:
    runs-on: ubuntu-latest
    outputs:
      container_url: ${{ steps.container-info.outputs.container-url }}
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Run Apache container
        id: run-container
        run: |
          docker run -d -p 8080:80 --name apache-container httpd:latest
          echo "Apache container is running"

      - name: Get container URL
        id: container-info
        run: echo "::set-output name=container-url::http://localhost:8080"

  curl-command:
    runs-on: ubuntu-latest
    needs: start-container
    steps:
      - name: Install curl
        run: sudo apt-get install -y curl

      - name: Run curl command
        run: |
          container_url=${{ needs.start-container.outputs.container_url }}
          echo "Sending curl request to $container_url"
          curl -X GET $container_url
