name: Create two containers and communicate via curl.

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Create Docker network
        run: docker network create my_network

    steps:
      - name: Run Apache container
        id: run-apache
        run: |
          docker run -d --network my_network --name apache-container httpd:latest
          echo "Apache container is running on network my_network"

  check-health-of-apache:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check container health
        id: check-health
        run: |
          for i in {1..10}; do
            if curl -s -o /dev/null -w "%{http_code}" http://apache-container:80 | grep -q "200"; then
              echo "Container is ready!"
              exit 0
            else
              echo "Waiting for container to be ready..."
              sleep 10
            fi
          done
          echo "Container did not become ready in time."
          exit 1

  check-connection:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Install curl
        run: sudo apt-get install -y curl

      - name: Check connection to Apache container
        run: |
          curl -I http://apache-container:80

