name: Docker Network Example

on: [push]

jobs:
  run-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Create Docker network
        run: docker network create my_network

      - name: Generate Docker Compose file
        run: |
          echo 'version: "3.8"
          services:
            apache:
              image: httpd:latest
              networks:
                - my_network
            another:
              image: curlimages/curl:latest
              networks:
                - my_network
          networks:
            my_network:
              driver: bridge' > docker-compose.yml

      - name: Run Docker Compose
        run: docker-compose up -d

      - name: Check connection to Apache container
        run: |
          curl -I http://apache:80

      - name: Check connection to Another container
        run: |
          curl -I http://another:some-port

      - name: Clean up Docker Compose
        run: |
          docker-compose down
          docker network rm my_network
