name: Example Workflow

on: [push]

jobs:
  start-container:
    runs-on: ubuntu-latest
    outputs:
      container-url: ${{ steps.get-url.outputs.container-url }}
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run Apache container
        id: run-container
        run: |
          docker network create my_network
          docker run -d --network my_network --name apache-container httpd:latest
          echo "Apache container is running on network my_network"

      - name: Get container URL
        id: get-url
        run: echo "::set-output name=container-url::http://apache-container:80"

      - name: Check container health
        id: check-health
        run: |
          for i in {1..10}; do
            if curl -s -o /dev/null -w "%{http_code}" http://apache-container:80 | grep -q "200"; then
              echo "Container is ready!"
              exit 0
            else
              echo "Waiting for container to be ready..."
              sleep 10
            fi
          done
          echo "Container did not become ready in time."
          exit 1

  curl-command:
    runs-on: ubuntu-latest
    needs: check-health
    steps:

      - name: Install curl
        run: sudo apt-get install -y curl

      - name: Run curl command
        run: |
          curl -X GET $CONTAINER_URL

  stop-container:
    runs-on: ubuntu-latest
    needs: curl-command
    steps:
      - name: Stop and remove Docker container
        run: |
          docker stop apache-container
          docker rm apache-container
          docker network rm my_network
